name: atba
description: "A TorBox Client"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  android_intent_plus: ^5.3.1
  app_links: ^6.4.1
  async: ^2.13.0
  build_runner: ^2.10.1
  collection: ^1.19.0
  crypto: ^3.0.6
  dartz: ^0.10.1
  dio: ^5.9.0
  dio_cache_interceptor: ^4.0.3
  drift: ^2.29.0
  dynamic_color: ^1.8.1
  either_dart: ^1.0.0
  file_picker: ^10.3.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_inappwebview: ^6.1.5
  flutter_launcher_icons: ^0.14.4
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^10.0.0
  # TODO: Can use official release after merge of https://github.com/GAM3RG33K/flutter_settings_screens/pull/126, but library is unmaintained
  flutter_settings_screens: 
    git:
      url: https://github.com/agersant/flutter_settings_screens.git
      ref: nested
  flutter_speed_dial: ^7.0.0
  http: ^1.4.0
  http_cache_client: ^1.0.2
  http_cache_core: ^1.1.1
  http_cache_drift_store: ^7.0.0
  http_cache_file_store: ^2.0.1
  http_cache_hive_store: ^5.0.1
  http_cache_sembast_store: ^1.0.0
  icon_craft: ^0.1.1
  json_annotation: ^4.9.0
  listen_sharing_intent: ^1.9.2
  package_info_plus: ^8.3.1
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  sqlite3_flutter_libs: ^0.5.40
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  webview_flutter: ^4.13.0
  memoized: ^2.2.6
  icons_plus: ^5.0.0
  background_downloader: ^9.4.1
  media_kit_video: ^2.0.1
  media_kit: ^1.2.6
  media_kit_libs_video: ^1.0.7
  sqlite3: ^2.9.4
  web: ^1.1.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.1
  drift_dev: ^2.29.0

flutter:
  assets:
    - assets/icons/
  uses-material-design: true
  fonts:
  - family: inter
    fonts:
      - asset: fonts/inter-Regular.ttf
  - family: torbox-dotted
    fonts:
      - asset: fonts/torbox-dotted-Regular.ttf
  - family: torbox-dotted-all
    fonts:
      - asset: fonts/torbox-dotted-all-Regular.ttf
